### ISSUE TITLE
find method to extend

### ISSUE THREAD

**Issue by kotbegemot** [duckstax/otterbrix#178]
Implement, by analogy with the $eq function, the following functions for find (in the find_condition module):

- [ ] 1. $nor logical NOR
- [ ] 2. $exists checking the presence of a field in the document
- [ ] 3. $type checking the type of the document field
- [ ] 4. Write tests to test each function

**Comment by jramine** [comment]
I would like to work on this

**Comment by kotbegemot** [comment]
I'm really glad to hear from you! Sorry for missing your message at first. Our team thinks switching the API to SQL isn't needed, but I can switch it back to the new interface no problem. How can I help out?
